import * as THREE from '../node_modules/three/build/three.module.js';
import { GLTFLoader } from '../node_modules/three/examples/jsm/loaders/GLTFLoader.js';

const $ = (id) => document.getElementById(id); const messages = $('messages'); let imageBase64 = null; let recognition = null; const referenceImage = document.createElement('img'); referenceImage.alt = 'Uploaded diagram reference'; referenceImage.id = 'reference-image'; $('viewport').prepend(referenceImage);
const accurateButton = document.createElement('button'); accurateButton.className = 'outline'; accurateButton.textContent = '⌁ Find accurate model'; $('upload').before(accurateButton); const localModelButton = document.createElement('button'); localModelButton.className = 'outline'; localModelButton.textContent = '＋ Open 3D model'; $('upload').before(localModelButton);
function addMessage(role, text) { const el = document.createElement('div'); el.className = `message ${role}`; el.innerHTML = `<div class="avatar">${role === 'user' ? '●' : '✦'}</div><p>${text.replaceAll('<', '&lt;')}</p>`; messages.append(el); messages.scrollTop = messages.scrollHeight; }
addMessage('assistant', 'I’m Lunar. Ask me anything, or upload a diagram and I’ll turn its structure into a rough 3D scene.');

async function checkStatus() { const state = await window.lunar.status(); $('status-dot').className = state.online ? 'online' : 'offline'; $('status-label').textContent = state.online ? `Gemma online · ${state.model}` : 'Ollama offline'; }
checkStatus();
async function createScene(prompt, image = null) {
  $('generate').disabled = true;
  try {
    const spec = await window.lunar.scene({ image, prompt: `${prompt}\n\nCreate an approximate 3D model for the workspace. Return an object with an objects array. Each object needs name, primitive (box, sphere, cylinder, plane), position [x,y,z], scale [x,y,z], and color hex.` });
    if (/heart|cardiac|atrium|ventricle|valve/i.test(prompt)) await loadAccurateModel(); else if (/airplane|aircraft|plane|jet/i.test(prompt)) renderAirplaneScene(); else renderScene(normalizeScene(spec));
    addMessage('assistant', 'I created an editable 3D draft in the scene workspace. Drag the preview to orbit it.');
  } catch (error) { addMessage('system', 'I could not create the 3D draft. Try uploading the diagram as an image or ask for a simpler diagram.'); }
  $('generate').disabled = !imageBase64;
}
$('composer').addEventListener('submit', async (event) => { event.preventDefault(); const input = $('prompt'); const text = input.value.trim(); if (!text) return; input.value = ''; addMessage('user', text); try { const reply = await window.lunar.chat(text); addMessage('assistant', reply.length > 900 ? `${reply.slice(0, 900).trim()}…` : reply); if (/\b(make|create|build|generate|model|render|design|3d|diagram|object|airplane|aircraft|heart|anatom|structure|system|graph)\b/i.test(text + ' ' + reply)) { group.clear(); await createScene(`${text}\nModel response:\n${reply}`, imageBase64); } } catch { addMessage('system', 'I could not reach Ollama. Start it with `ollama serve`, then try again.'); } });
$('mic').addEventListener('click', () => { if (!('webkitSpeechRecognition' in window)) return addMessage('system', 'Speech recognition is unavailable in this Electron build.'); if (recognition) { recognition.stop(); return; } recognition = new webkitSpeechRecognition(); recognition.continuous = false; recognition.interimResults = false; recognition.onresult = (event) => { $('prompt').value = event.results[0][0].transcript; $('composer').requestSubmit(); }; recognition.onend = () => { recognition = null; $('mic').classList.remove('recording'); }; recognition.start(); $('mic').classList.add('recording'); });

$('upload').addEventListener('click', async () => { const file = await window.lunar.pickImage(); if (!file) return; imageBase64 = await window.lunar.readImage(file); const extension = file.split('.').pop().toLowerCase(); const mime = extension === 'png' ? 'image/png' : extension === 'webp' ? 'image/webp' : 'image/jpeg'; referenceImage.src = `data:${mime};base64,${imageBase64}`; referenceImage.classList.add('visible'); $('diagram-label').textContent = file.split('/').pop(); $('generate').disabled = false; });
$('generate').addEventListener('click', () => createScene('Analyze the uploaded diagram as a coarse 3D scene.', imageBase64));
accurateButton.addEventListener('click', () => loadAccurateModel());
localModelButton.addEventListener('click', async () => { const file = await window.lunar.pickModel(); if (!file) return; try { const bytes = await window.lunar.readModel(file); await loadModelBytes(bytes, file.split('.').pop().toLowerCase()); addMessage('assistant', `Loaded ${file.split('/').pop()} into the 3D workspace.`); } catch (error) { addMessage('system', `This model could not be opened: ${error.message || 'unsupported format'}`); } });

const scene = new THREE.Scene(); const camera = new THREE.PerspectiveCamera(42, 1, .1, 100); camera.position.set(0, .5, 9); const renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true }); renderer.setPixelRatio(devicePixelRatio); renderer.outputColorSpace = THREE.SRGBColorSpace; $('viewport').append(renderer.domElement); const group = new THREE.Group(); scene.add(group); scene.add(new THREE.HemisphereLight(0xffeee8, 0x18202c, 2.4)); const light = new THREE.DirectionalLight(0xffd9ba, 3.5); light.position.set(3, 5, 5); scene.add(light); let dragging = false, lastX = 0; $('viewport').addEventListener('pointerdown', (e) => { dragging = true; lastX = e.clientX; }); window.addEventListener('pointerup', () => dragging = false); window.addEventListener('pointermove', (e) => { if (dragging) { group.rotation.y += (e.clientX - lastX) * .01; lastX = e.clientX; } });
async function loadModelBytes(bytes, extension = 'glb') { if (extension !== 'glb' && extension !== 'gltf') throw new Error('Use GLB or GLTF for local models right now'); const loader = new GLTFLoader(); const buffer = bytes instanceof Uint8Array ? bytes.buffer : bytes; const gltf = await new Promise((resolve, reject) => loader.parse(buffer, '', resolve, reject)); const model = gltf.scene; model.traverse((node) => { if (node.isMesh) { node.castShadow = true; node.receiveShadow = true; if (node.material) { node.material = node.material.clone(); node.material.roughness = .42; node.material.metalness = .02; } } }); const box = new THREE.Box3().setFromObject(model); const size = box.getSize(new THREE.Vector3()); const center = box.getCenter(new THREE.Vector3()); const scale = 4.8 / Math.max(size.x, size.y, size.z); model.scale.setScalar(scale); model.position.sub(center.multiplyScalar(scale)); group.clear(); group.add(model); }
async function loadAccurateModel() { accurateButton.disabled = true; accurateButton.textContent = 'Loading NIH model…'; try { const bytes = await window.lunar.fetchAccurateModel(); await loadModelBytes(bytes); addMessage('assistant', 'Loaded the NIH 3D heart reference model. This is a source-backed anatomical asset; drag to orbit it.'); } catch (error) { renderHeartScene(); addMessage('system', `The online model source returned an error (${error.message || 'unavailable'}). Showing Lunar’s detailed heart fallback instead.`); } accurateButton.disabled = false; accurateButton.textContent = '⌁ Find accurate model'; }
function normalizeScene(spec) { const objects = Array.isArray(spec) ? spec : spec.objects || spec.components || spec.parts || []; return { objects: objects.map((item, index) => ({ name: item.name || `Part ${index + 1}`, primitive: item.primitive || item.type || 'box', position: item.position || [0, index * 0.8, 0], scale: item.scale || [1, 1, 1], color: item.color || ['#e8a878', '#6d9dc5', '#9dc27c', '#c88ed4'][index % 4] })) }; }
function renderHeartScene() {
  group.clear();
  const heartMaterial = new THREE.MeshPhysicalMaterial({ color: '#9f3445', roughness: .28, metalness: .02, clearcoat: .45, clearcoatRoughness: .2, transparent: true, opacity: .34, depthWrite: false, side: THREE.DoubleSide });
  const profile = [[0, -1.55], [.34, -1.5], [.72, -1.25], [1.08, -.78], [1.28, -.1], [1.32, .52], [1.2, 1.02], [.96, 1.45], [.58, 1.7], [0, 1.76]].map(([radius, y]) => new THREE.Vector2(radius, y));
  const heart = new THREE.Mesh(new THREE.LatheGeometry(profile, 64), heartMaterial); heart.scale.set(.96, 1, .82); heart.rotation.x = -.08; heart.rotation.y = -.16; heart.position.x = .02; group.add(heart);
  const lobeMaterial = heartMaterial.clone(); lobeMaterial.opacity = .42; const lobe = (x, y, z, scale) => { const node = new THREE.Mesh(new THREE.SphereGeometry(1, 40, 24), lobeMaterial); node.position.set(x, y, z); node.scale.set(...scale); group.add(node); }; lobe(-.52, 1.16, .08, [.66, .64, .66]); lobe(.48, 1.28, .1, [.72, .72, .7]);
  const chamber = (x, y, z, color, scale) => { const node = new THREE.Mesh(new THREE.SphereGeometry(.32, 32, 24), new THREE.MeshPhysicalMaterial({ color, roughness: .3, clearcoat: .35 })); node.position.set(x, y, z); node.scale.set(...scale); group.add(node); };
  chamber(-.47, .42, 1.02, '#5c8cbd', [.9, .7, .32]); chamber(.47, .42, 1.02, '#c75a58', [.9, .7, .32]); chamber(-.47, -.42, 1.08, '#4776aa', [1.02, 1.12, .34]); chamber(.47, -.42, 1.08, '#b8424b', [1.02, 1.12, .34]);
  const septum = new THREE.Mesh(new THREE.BoxGeometry(.055, 1.65, .06), new THREE.MeshPhysicalMaterial({ color: '#f0b18a', roughness: .3, clearcoat: .25 })); septum.position.set(0, -.08, 1.38); septum.rotation.z = -.08; group.add(septum);
  const tube = (points, radius, color) => { const curve = new THREE.CatmullRomCurve3(points.map(([x, y, z]) => new THREE.Vector3(x, y, z))); const node = new THREE.Mesh(new THREE.TubeGeometry(curve, 32, radius, 12, false), new THREE.MeshPhysicalMaterial({ color, roughness: .24, clearcoat: .5 })); group.add(node); };
  tube([[-.8, .9, 1.08], [-.25, .62, 1.1], [.1, .2, 1.12], [.45, -.18, 1.1], [.75, -.62, 1.04]], .045, '#641e2b'); tube([[.8, .82, 1.06], [.25, .55, 1.1], [-.1, .05, 1.13], [-.42, -.55, 1.06]], .038, '#701f2d');
  tube([[-.74, 1.18, .1], [-1.15, 1.55, .1], [-1.1, 1.95, .1], [-.82, 2.18, .1]], .22, '#b94a50'); tube([[.35, 1.28, .12], [.65, 1.68, .12], [.45, 2.08, .12], [.15, 2.3, .12]], .2, '#c95858');
  tube([[.15, 2.28, .12], [.45, 2.53, .12], [.83, 2.52, .12]], .13, '#cf6860'); tube([[.32, 2.35, .12], [.75, 2.76, .12], [1.1, 2.72, .12]], .11, '#cf6860'); tube([[.5, 2.38, .12], [.95, 2.95, .12], [1.18, 2.96, .12]], .1, '#cf6860');
  const valveMaterial = new THREE.MeshPhysicalMaterial({ color: '#e8b66b', roughness: .25, clearcoat: .4 }); const valve = new THREE.Mesh(new THREE.TorusGeometry(.17, .06, 16, 32), valveMaterial); valve.position.set(-.43, -.04, 1.42); valve.rotation.x = Math.PI / 2; group.add(valve); const valve2 = valve.clone(); valve2.position.x = .43; group.add(valve2);
  group.scale.set(.82, .82, .82); group.position.y = -.25;
}

function renderAirplaneScene() {
  group.clear();
  const metal = new THREE.MeshPhysicalMaterial({ color: '#d8e1eb', roughness: .24, metalness: .18, clearcoat: .5 }); const dark = new THREE.MeshPhysicalMaterial({ color: '#26384e', roughness: .25, metalness: .3 }); const blue = new THREE.MeshPhysicalMaterial({ color: '#477da8', roughness: .28, metalness: .15 });
  const add = (geometry, material, position, rotation = [0, 0, 0], scale = [1, 1, 1]) => { const node = new THREE.Mesh(geometry, material); node.position.set(...position); node.rotation.set(...rotation); node.scale.set(...scale); group.add(node); return node; };
  add(new THREE.CylinderGeometry(.46, .52, 4.8, 32), metal, [0, 0, 0], [0, 0, Math.PI / 2]);
  add(new THREE.ConeGeometry(.46, 1.15, 32), metal, [2.95, 0, 0], [0, 0, -Math.PI / 2]); add(new THREE.SphereGeometry(.48, 32, 20), metal, [-2.3, 0, 0], [0, 0, 0], [1.2, .95, .95]);
  add(new THREE.BoxGeometry(3.2, .12, 7.4), blue, [.15, -.05, 0], [0, 0, 0], [1, 1, .72]); add(new THREE.BoxGeometry(1.6, .1, 3.2), blue, [-1.7, .72, 0], [0, 0, 0], [1, 1, .55]);
  add(new THREE.BoxGeometry(1.2, .12, 2.4), metal, [-1.82, .72, 0], [0, 0, 0], [1, 1, .45]);
  for (const z of [-1.62, 1.62]) { add(new THREE.CylinderGeometry(.3, .34, 1.15, 24), dark, [.25, -.52, z], [Math.PI / 2, 0, 0]); add(new THREE.TorusGeometry(.3, .07, 12, 24), metal, [.25, -.52, z], [Math.PI / 2, 0, 0]); }
  for (let i = -2; i <= 2; i++) add(new THREE.BoxGeometry(.16, .12, .32), dark, [1.9 - i * .5, .43, -.48], [0, 0, 0]);
  group.rotation.y = -.25; group.rotation.x = .08; group.scale.setScalar(.72); group.position.y = -.15;
}
function renderScene(spec) { group.clear(); normalizeScene(spec).objects.forEach((item) => { const geometry = item.primitive === 'sphere' ? new THREE.SphereGeometry(.65, 32, 20) : item.primitive === 'cylinder' ? new THREE.CylinderGeometry(.55, .55, 1.2, 32) : item.primitive === 'plane' ? new THREE.PlaneGeometry(1, 1) : new THREE.BoxGeometry(1, 1, 1); const mesh = new THREE.Mesh(geometry, new THREE.MeshStandardMaterial({ color: item.color || '#e8a878', roughness: .55 })); mesh.position.set(...(item.position || [0, 0, 0])); mesh.scale.set(...(item.scale || [1, 1, 1])); group.add(mesh); }); }
renderScene({ objects: [{ primitive: 'box', position: [0, 0, 0], scale: [2.2, .7, 1.4], color: '#e8a878' }, { primitive: 'cylinder', position: [0, -1, 0], scale: [.5, 1, .5], color: '#6d9dc5' }] });
function resize() { const box = $('viewport').getBoundingClientRect(); camera.aspect = box.width / box.height; camera.updateProjectionMatrix(); renderer.setSize(box.width, box.height); } new ResizeObserver(resize).observe($('viewport')); resize(); (function animate() { requestAnimationFrame(animate); renderer.render(scene, camera); })();
