import * as THREE from '../node_modules/three/build/three.module.js';
import { GLTFLoader } from '../node_modules/three/examples/jsm/loaders/GLTFLoader.js';

const $ = (id) => document.getElementById(id); const messages = $('messages'); let imageBase64 = null; let recognition = null; const referenceImage = document.createElement('img'); referenceImage.alt = 'Uploaded diagram reference'; referenceImage.id = 'reference-image'; $('viewport').prepend(referenceImage);
const accurateButton = document.createElement('button'); accurateButton.className = 'outline'; accurateButton.textContent = '⌁ Find accurate model'; $('upload').before(accurateButton);
function addMessage(role, text) { const el = document.createElement('div'); el.className = `message ${role}`; el.innerHTML = `<div class="avatar">${role === 'user' ? '●' : '✦'}</div><p>${text.replaceAll('<', '&lt;')}</p>`; messages.append(el); messages.scrollTop = messages.scrollHeight; }
addMessage('assistant', 'I’m Lunar. Ask me anything, or upload a diagram and I’ll turn its structure into a rough 3D scene.');

async function checkStatus() { const state = await window.lunar.status(); $('status-dot').className = state.online ? 'online' : 'offline'; $('status-label').textContent = state.online ? `Gemma online · ${state.model}` : 'Ollama offline'; }
checkStatus();
async function createScene(prompt, image = null) {
  $('generate').disabled = true;
  try {
    const spec = await window.lunar.scene({ image, prompt: `${prompt}\n\nCreate an approximate 3D model for the workspace. Return an object with an objects array. Each object needs name, primitive (box, sphere, cylinder, plane), position [x,y,z], scale [x,y,z], and color hex.` });
    if (/heart|cardiac|atrium|ventricle|valve/i.test(prompt)) renderHeartScene(); else renderScene(normalizeScene(spec));
    addMessage('assistant', 'I created an editable 3D draft in the scene workspace. Drag the preview to orbit it.');
  } catch (error) { addMessage('system', 'I could not create the 3D draft. Try uploading the diagram as an image or ask for a simpler diagram.'); }
  $('generate').disabled = !imageBase64;
}
$('composer').addEventListener('submit', async (event) => { event.preventDefault(); const input = $('prompt'); const text = input.value.trim(); if (!text) return; input.value = ''; addMessage('user', text); try { const reply = await window.lunar.chat(text); addMessage('assistant', reply.length > 900 ? `${reply.slice(0, 900).trim()}…` : reply); if (/diagram|flowchart|mermaid|svg|anatom|heart|cardiac|structure|system|graph/i.test(text + ' ' + reply)) await createScene(`${text}\nModel response:\n${reply}`, imageBase64); } catch { addMessage('system', 'I could not reach Ollama. Start it with `ollama serve`, then try again.'); } });
$('mic').addEventListener('click', () => { if (!('webkitSpeechRecognition' in window)) return addMessage('system', 'Speech recognition is unavailable in this Electron build.'); if (recognition) { recognition.stop(); return; } recognition = new webkitSpeechRecognition(); recognition.continuous = false; recognition.interimResults = false; recognition.onresult = (event) => { $('prompt').value = event.results[0][0].transcript; $('composer').requestSubmit(); }; recognition.onend = () => { recognition = null; $('mic').classList.remove('recording'); }; recognition.start(); $('mic').classList.add('recording'); });

$('upload').addEventListener('click', async () => { const file = await window.lunar.pickImage(); if (!file) return; imageBase64 = await window.lunar.readImage(file); const extension = file.split('.').pop().toLowerCase(); const mime = extension === 'png' ? 'image/png' : extension === 'webp' ? 'image/webp' : 'image/jpeg'; referenceImage.src = `data:${mime};base64,${imageBase64}`; referenceImage.classList.add('visible'); $('diagram-label').textContent = file.split('/').pop(); $('generate').disabled = false; });
$('generate').addEventListener('click', () => createScene('Analyze the uploaded diagram as a coarse 3D scene.', imageBase64));
accurateButton.addEventListener('click', () => loadAccurateModel());

const scene = new THREE.Scene(); const camera = new THREE.PerspectiveCamera(42, 1, .1, 100); camera.position.set(0, .5, 9); const renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true }); renderer.setPixelRatio(devicePixelRatio); renderer.outputColorSpace = THREE.SRGBColorSpace; $('viewport').append(renderer.domElement); const group = new THREE.Group(); scene.add(group); scene.add(new THREE.HemisphereLight(0xffeee8, 0x18202c, 2.4)); const light = new THREE.DirectionalLight(0xffd9ba, 3.5); light.position.set(3, 5, 5); scene.add(light); let dragging = false, lastX = 0; $('viewport').addEventListener('pointerdown', (e) => { dragging = true; lastX = e.clientX; }); window.addEventListener('pointerup', () => dragging = false); window.addEventListener('pointermove', (e) => { if (dragging) { group.rotation.y += (e.clientX - lastX) * .01; lastX = e.clientX; } });
async function loadAccurateModel() { accurateButton.disabled = true; accurateButton.textContent = 'Loading NIH model…'; try { group.clear(); const loader = new GLTFLoader(); const bytes = await window.lunar.fetchAccurateModel(); const buffer = bytes instanceof Uint8Array ? bytes.buffer : bytes; const gltf = await new Promise((resolve, reject) => loader.parse(buffer, '', resolve, reject)); const model = gltf.scene; model.traverse((node) => { if (node.isMesh) { node.castShadow = true; node.receiveShadow = true; if (node.material) { node.material = node.material.clone(); node.material.roughness = .42; node.material.metalness = .02; } } }); const box = new THREE.Box3().setFromObject(model); const size = box.getSize(new THREE.Vector3()); const center = box.getCenter(new THREE.Vector3()); const scale = 4.8 / Math.max(size.x, size.y, size.z); model.scale.setScalar(scale); model.position.sub(center.multiplyScalar(scale)); group.add(model); addMessage('assistant', 'Loaded the NIH 3D heart reference model. This is a source-backed anatomical asset; drag to orbit it.'); } catch (error) { addMessage('system', `The online model could not be loaded: ${error.message || 'unknown error'}`); } accurateButton.disabled = false; accurateButton.textContent = '⌁ Find accurate model'; }
function normalizeScene(spec) { const objects = Array.isArray(spec) ? spec : spec.objects || spec.components || spec.parts || []; return { objects: objects.map((item, index) => ({ name: item.name || `Part ${index + 1}`, primitive: item.primitive || item.type || 'box', position: item.position || [0, index * 0.8, 0], scale: item.scale || [1, 1, 1], color: item.color || ['#e8a878', '#6d9dc5', '#9dc27c', '#c88ed4'][index % 4] })) }; }
function renderHeartScene() {
  group.clear();
  const shape = new THREE.Shape(); shape.moveTo(0, -1.1); shape.bezierCurveTo(-2.3, .35, -1.45, 1.65, -.65, 1.55); shape.bezierCurveTo(-.2, 1.5, 0, 1.18, 0, 1.02); shape.bezierCurveTo(0, 1.18, .2, 1.5, .65, 1.55); shape.bezierCurveTo(1.45, 1.65, 2.3, .35, 0, -1.1);
  const heartMaterial = new THREE.MeshPhysicalMaterial({ color: '#9f3445', roughness: .28, metalness: .02, clearcoat: .45, clearcoatRoughness: .2, transparent: true, opacity: .34, depthWrite: false, side: THREE.DoubleSide });
  const heart = new THREE.Mesh(new THREE.ExtrudeGeometry(shape, { depth: 1.05, bevelEnabled: true, bevelSegments: 8, curveSegments: 16, bevelSize: .16, bevelThickness: .16 }), heartMaterial); heart.scale.set(.88, 1.06, 1); heart.rotation.x = -.08; heart.rotation.y = -.16; group.add(heart);
  const chamber = (x, y, z, color, scale) => { const node = new THREE.Mesh(new THREE.SphereGeometry(.32, 32, 24), new THREE.MeshPhysicalMaterial({ color, roughness: .3, clearcoat: .35 })); node.position.set(x, y, z); node.scale.set(...scale); group.add(node); };
  chamber(-.47, .42, 1.02, '#5c8cbd', [.9, .7, .32]); chamber(.47, .42, 1.02, '#c75a58', [.9, .7, .32]); chamber(-.47, -.42, 1.08, '#4776aa', [1.02, 1.12, .34]); chamber(.47, -.42, 1.08, '#b8424b', [1.02, 1.12, .34]);
  const septum = new THREE.Mesh(new THREE.BoxGeometry(.055, 1.65, .06), new THREE.MeshPhysicalMaterial({ color: '#f0b18a', roughness: .3, clearcoat: .25 })); septum.position.set(0, -.08, 1.38); septum.rotation.z = -.08; group.add(septum);
  const tube = (points, radius, color) => { const curve = new THREE.CatmullRomCurve3(points.map(([x, y, z]) => new THREE.Vector3(x, y, z))); const node = new THREE.Mesh(new THREE.TubeGeometry(curve, 32, radius, 12, false), new THREE.MeshPhysicalMaterial({ color, roughness: .24, clearcoat: .5 })); group.add(node); };
  tube([[-.8, .9, 1.08], [-.25, .62, 1.1], [.1, .2, 1.12], [.45, -.18, 1.1], [.75, -.62, 1.04]], .045, '#641e2b'); tube([[.8, .82, 1.06], [.25, .55, 1.1], [-.1, .05, 1.13], [-.42, -.55, 1.06]], .038, '#701f2d');
  tube([[-.74, 1.18, .1], [-1.15, 1.55, .1], [-1.1, 1.95, .1], [-.82, 2.18, .1]], .22, '#b94a50'); tube([[.35, 1.28, .12], [.65, 1.68, .12], [.45, 2.08, .12], [.15, 2.3, .12]], .2, '#c95858');
  tube([[.15, 2.28, .12], [.45, 2.53, .12], [.83, 2.52, .12]], .13, '#cf6860'); tube([[.32, 2.35, .12], [.75, 2.76, .12], [1.1, 2.72, .12]], .11, '#cf6860'); tube([[.5, 2.38, .12], [.95, 2.95, .12], [1.18, 2.96, .12]], .1, '#cf6860');
  const valveMaterial = new THREE.MeshPhysicalMaterial({ color: '#e8b66b', roughness: .25, clearcoat: .4 }); const valve = new THREE.Mesh(new THREE.TorusGeometry(.17, .06, 16, 32), valveMaterial); valve.position.set(-.43, -.04, 1.42); valve.rotation.x = Math.PI / 2; group.add(valve); const valve2 = valve.clone(); valve2.position.x = .43; group.add(valve2);
  group.scale.set(.82, .82, .82); group.position.y = -.25;
}
function renderScene(spec) { group.clear(); normalizeScene(spec).objects.forEach((item) => { const geometry = item.primitive === 'sphere' ? new THREE.SphereGeometry(.65, 32, 20) : item.primitive === 'cylinder' ? new THREE.CylinderGeometry(.55, .55, 1.2, 32) : item.primitive === 'plane' ? new THREE.PlaneGeometry(1, 1) : new THREE.BoxGeometry(1, 1, 1); const mesh = new THREE.Mesh(geometry, new THREE.MeshStandardMaterial({ color: item.color || '#e8a878', roughness: .55 })); mesh.position.set(...(item.position || [0, 0, 0])); mesh.scale.set(...(item.scale || [1, 1, 1])); group.add(mesh); }); }
renderScene({ objects: [{ primitive: 'box', position: [0, 0, 0], scale: [2.2, .7, 1.4], color: '#e8a878' }, { primitive: 'cylinder', position: [0, -1, 0], scale: [.5, 1, .5], color: '#6d9dc5' }] });
function resize() { const box = $('viewport').getBoundingClientRect(); camera.aspect = box.width / box.height; camera.updateProjectionMatrix(); renderer.setSize(box.width, box.height); } new ResizeObserver(resize).observe($('viewport')); resize(); (function animate() { requestAnimationFrame(animate); renderer.render(scene, camera); })();
