import * as THREE from '../node_modules/three/build/three.module.js';

const $ = (id) => document.getElementById(id); const messages = $('messages'); let imageBase64 = null; let recognition = null;
function addMessage(role, text) { const el = document.createElement('div'); el.className = `message ${role}`; el.innerHTML = `<div class="avatar">${role === 'user' ? '●' : '✦'}</div><p>${text.replaceAll('<', '&lt;')}</p>`; messages.append(el); messages.scrollTop = messages.scrollHeight; }
addMessage('assistant', 'I’m Lunar. Ask me anything, or upload a diagram and I’ll turn its structure into a rough 3D scene.');

async function checkStatus() { const state = await window.lunar.status(); $('status-dot').className = state.online ? 'online' : 'offline'; $('status-label').textContent = state.online ? `Gemma online · ${state.model}` : 'Ollama offline'; }
checkStatus();
$('composer').addEventListener('submit', async (event) => { event.preventDefault(); const input = $('prompt'); const text = input.value.trim(); if (!text) return; input.value = ''; addMessage('user', text); try { addMessage('assistant', await window.lunar.chat(text)); } catch { addMessage('system', 'I could not reach Ollama. Start it with `ollama serve`, then try again.'); } });
$('mic').addEventListener('click', () => { if (!('webkitSpeechRecognition' in window)) return addMessage('system', 'Speech recognition is unavailable in this Electron build.'); if (recognition) { recognition.stop(); return; } recognition = new webkitSpeechRecognition(); recognition.continuous = false; recognition.interimResults = false; recognition.onresult = (event) => { $('prompt').value = event.results[0][0].transcript; $('composer').requestSubmit(); }; recognition.onend = () => { recognition = null; $('mic').classList.remove('recording'); }; recognition.start(); $('mic').classList.add('recording'); });

$('upload').addEventListener('click', async () => { const file = await window.lunar.pickImage(); if (!file) return; imageBase64 = await window.lunar.readImage(file); $('diagram-label').textContent = file.split('/').pop(); $('generate').disabled = false; });
$('generate').addEventListener('click', async () => { $('generate').disabled = true; try { const spec = await window.lunar.scene({ image: imageBase64, prompt: 'Analyze this diagram as a coarse 3D scene. Return an object with an objects array. Each object needs name, primitive (box, sphere, cylinder, plane), position [x,y,z], scale [x,y,z], and color hex.' }); renderScene(spec); addMessage('assistant', 'I made an editable 3D draft from the diagram. Orbit it in the preview.'); } catch { addMessage('system', 'The diagram could not be interpreted, so I kept the starter scene.'); } $('generate').disabled = false; });

const scene = new THREE.Scene(); const camera = new THREE.PerspectiveCamera(42, 1, .1, 100); camera.position.set(0, 2, 7); const renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true }); renderer.setPixelRatio(devicePixelRatio); $('viewport').append(renderer.domElement); const group = new THREE.Group(); scene.add(group); scene.add(new THREE.HemisphereLight(0xffffff, 0x1d2430, 2)); const light = new THREE.DirectionalLight(0xffd9ba, 3); light.position.set(3, 5, 4); scene.add(light); let dragging = false, lastX = 0; $('viewport').addEventListener('pointerdown', (e) => { dragging = true; lastX = e.clientX; }); window.addEventListener('pointerup', () => dragging = false); window.addEventListener('pointermove', (e) => { if (dragging) { group.rotation.y += (e.clientX - lastX) * .01; lastX = e.clientX; } });
function renderScene(spec) { group.clear(); (spec.objects || []).forEach((item) => { const geometry = item.primitive === 'sphere' ? new THREE.SphereGeometry(.65, 32, 20) : item.primitive === 'cylinder' ? new THREE.CylinderGeometry(.55, .55, 1.2, 32) : new THREE.BoxGeometry(1, 1, 1); const mesh = new THREE.Mesh(geometry, new THREE.MeshStandardMaterial({ color: item.color || '#e8a878', roughness: .55 })); mesh.position.set(...(item.position || [0, 0, 0])); mesh.scale.set(...(item.scale || [1, 1, 1])); group.add(mesh); }); }
renderScene({ objects: [{ primitive: 'box', position: [0, 0, 0], scale: [2.2, .7, 1.4], color: '#e8a878' }, { primitive: 'cylinder', position: [0, -1, 0], scale: [.5, 1, .5], color: '#6d9dc5' }] });
function resize() { const box = $('viewport').getBoundingClientRect(); camera.aspect = box.width / box.height; camera.updateProjectionMatrix(); renderer.setSize(box.width, box.height); } new ResizeObserver(resize).observe($('viewport')); resize(); (function animate() { requestAnimationFrame(animate); renderer.render(scene, camera); })();
